### ISSUE TITLE
Working on Python 2/3 cross-compatibility

### ISSUE THREAD

**Issue by MatthieuDartiailh** [peterazmanov/enaml#20]
Hi,
I would like to help in supporting both python 2 and 3. I have seen that you tagged some issues as being relevant for that but there are not very detailed. Can you give me some pointers about where I could start looking ?

Thanks

PS : Is your fork of Atom currently supporting both ?

**Comment by peterazmanov** [comment]
Thanks for your interest. My version of Atom is based on work of @dwillmer which I believe is 2+3 compatible, however several commits that I added above to fix support of py3k are py3k only, so there is some work to do there (one of commits changes Atom data types, I added 'Bytes' data type and made 'Str' alias to 'Unicode' to reflect changes in py3k, I think the easiest way to handle this is to support these changes in python 2).

**Comment by peterazmanov** [comment]
Enaml issues are separated in two groups: issues about lack of support of (or bugs in) py3k features in enaml files and issues which labeled '2+3' about lack of cross compatibility.

**Comment by peterazmanov** [comment]
Currently I'm working on making byteplay more robust for py3k version. I'm testing it on Python library. There are problems with calculation of stack size for try/except/finally blocks.

**Comment by MatthieuDartiailh** [comment]
I will try to start by working on Atom. Hopefully it will straightforward. Then I will try to run my projects tests undr python 2 and using your version and see what I need to fix.
Another question have you plan for supporting both pyqt4 and 5 ?

**Comment by MatthieuDartiailh** [comment]
I started looking into Atom. Should be fairly easy to get working. I use the future project to provide a compatibility layer (needed for metaclass support). I was thinking for bytes/str/unicode we could port the solution adopted by @sccolbert in the atom-1.0.0dev branch. We could also used the minimal C compat layer in introduced there to make our life easier. WDYT ?

**Comment by peterazmanov** [comment]
I agree to both propositions. My fault, I didn't consult dev-branch while porting.

**Comment by MatthieuDartiailh** [comment]
#21 is a first cut at cross-compatibility. The next big step will be to fix the byteplay/parsing issues. Do you have any plans concerning those two points ?

**Comment by peterazmanov** [comment]
If you are probably aware there were some improvements in [main byteplay development repo](https://github.com/serprex/byteplay), after my work was pulled by owner. There is now `setup.py`. One easy step left: create root byteplay module to choose between different modules for different Python versions and upload repo to pypi, although I prefer the uploading would be done after several people would test byteplay with Python 3.4/3.5.

I have no immediate plans regarding cross-compatibility support. It wasn't my priority in the first place ). The development of the project I am working on will be ceased due to restructuring of our company. It doesn't mean I won't participate in enaml development. I believe enaml is a promising project. The amount of time which I will dedicate to it will be limited for indefinite period. Though I will review and test any pull requests and fix bugs if there will be any.

**Comment by MatthieuDartiailh** [comment]
Will be fixed in the original repo by https://github.com/nucleic/enaml/pull/227
